import { ALLOWED_STATUSES, sanitizeSettingValue, sanitizeStatus, validateBooking } from './validation.js';

const PUBLIC_SETTING_KEYS = [
  'price_published','price_note','price_bathSpa','price_grooming','price_bathGrooming','price_hotelPerNight','price_earCleaning','price_glandCleaning','hotel_capacity','hotel_capacity_published'
];
const SETTING_KEYS = new Set(PUBLIC_SETTING_KEYS);
const MAX_BODY_BYTES = 24000;

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}})}
function allowedOrigins(env){return String(env.ALLOWED_ORIGINS||'https://capquangfptminhlh.github.io,http://localhost:8788,http://127.0.0.1:8788').split(',').map(v=>v.trim()).filter(Boolean)}
function corsFor(request,env){const origin=request.headers.get('Origin');const allowed=allowedOrigins(env);if(!origin)return{ok:true,headers:{}};if(!allowed.includes(origin))return{ok:false,headers:{}};return{ok:true,headers:{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PATCH,PUT,OPTIONS','access-control-allow-headers':'content-type,authorization','access-control-max-age':'86400',vary:'Origin'}}}
function withCors(response,headers){const next=new Headers(response.headers);Object.entries(headers||{}).forEach(([k,v])=>next.set(k,v));return new Response(response.body,{status:response.status,statusText:response.statusText,headers:next})}
function adminAuthorized(request,env){if(!env.ADMIN_TOKEN)return false;return (request.headers.get('Authorization')||'')===`Bearer ${env.ADMIN_TOKEN}`}
function codeFor(type){const d=new Date();const ymd=d.toISOString().slice(0,10).replace(/-/g,'');const rand=crypto.randomUUID().replace(/-/g,'').slice(0,4).toUpperCase();return `LUMI-${type==='hotel'?'HOTEL':'CARE'}-${ymd}-${rand}`}
async function parseJson(request){const len=Number(request.headers.get('content-length')||0);if(len>MAX_BODY_BYTES)throw new Error('BODY_TOO_LARGE');const text=await request.text();if(text.length>MAX_BODY_BYTES)throw new Error('BODY_TOO_LARGE');if(!text)return{};try{return JSON.parse(text)}catch{throw new Error('BODY_INVALID_JSON')}}
async function getSettings(db,keys=PUBLIC_SETTING_KEYS){if(!keys.length)return{};const placeholders=keys.map(()=>'?').join(',');const{results}=await db.prepare(`SELECT key, value FROM settings WHERE key IN (${placeholders})`).bind(...keys).run();return Object.fromEntries((results||[]).map(row=>[row.key,row.value]))}
function publicConfig(settings){const published=settings.price_published==='true';const capacityPublished=settings.hotel_capacity_published==='true';const toPrice=key=>{if(!published)return null;const value=Number(settings[key]);return Number.isFinite(value)&&value>0?value:null};const capacity=Number(settings.hotel_capacity);return{prices:{published,note:settings.price_note||'Giá được Lumi xác nhận theo thông tin thực tế của bé.',bathSpa:toPrice('price_bathSpa'),grooming:toPrice('price_grooming'),bathGrooming:toPrice('price_bathGrooming'),hotelPerNight:toPrice('price_hotelPerNight'),earCleaning:toPrice('price_earCleaning'),glandCleaning:toPrice('price_glandCleaning')},hotel:{capacityPublished,capacity:capacityPublished&&Number.isInteger(capacity)&&capacity>0?capacity:null},bookingStatus:'REQUEST_ONLY'}}
async function insertBooking(db,input){const code=input.code||codeFor(input.type);const now=new Date().toISOString();if(input.type==='appointment'){await db.prepare(`INSERT INTO bookings (code,created_at,updated_at,type,status,owner_name,phone,pet_name,pet_type,weight_kg,quantity,service,appointment_date,appointment_time,note,source) VALUES (?1,?2,?2,'appointment','PENDING_CONFIRMATION',?3,?4,?5,?6,?7,1,?8,?9,?10,?11,?12)`).bind(code,now,input.owner,input.phone,input.pet,input.petType,input.weight,input.service,input.appointmentDate,input.appointmentTime,input.note,input.source).run()}else{await db.prepare(`INSERT INTO bookings (code,created_at,updated_at,type,status,owner_name,phone,pet_name,pet_type,quantity,checkin_date,checkin_time,checkout_date,checkout_time,nights,food_notes,note,source) VALUES (?1,?2,?2,'hotel','PENDING_CONFIRMATION',?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15)`).bind(code,now,input.owner,input.phone,input.pet,input.petType,input.quantity,input.checkinDate,input.checkinTime,input.checkoutDate,input.checkoutTime,input.nights,input.food,input.note,input.source).run()}return{code,status:'PENDING_CONFIRMATION',createdAt:now}}
async function publicAvailability(db,url){const start=url.searchParams.get('start'),end=url.searchParams.get('end');if(!/^\d{4}-\d{2}-\d{2}$/.test(start||'')||!/^\d{4}-\d{2}-\d{2}$/.test(end||'')||end<=start)return json({error:'DATE_RANGE_INVALID'},400);const config=publicConfig(await getSettings(db));if(!config.hotel.capacityPublished||!config.hotel.capacity)return json({status:'CONTACT_REQUIRED',capacity:null,confirmedUnits:null,pendingUnits:null,availableEstimate:null});const{results}=await db.prepare(`SELECT status,COALESCE(SUM(quantity),0) AS units FROM bookings WHERE type='hotel' AND status IN ('PENDING_CONFIRMATION','CONFIRMED') AND checkin_date < ?1 AND checkout_date > ?2 GROUP BY status`).bind(end,start).run();const byStatus=Object.fromEntries((results||[]).map(row=>[row.status,Number(row.units||0)]));const confirmedUnits=byStatus.CONFIRMED||0,pendingUnits=byStatus.PENDING_CONFIRMATION||0;return json({status:'ESTIMATE_ONLY',capacity:config.hotel.capacity,confirmedUnits,pendingUnits,availableEstimate:Math.max(0,config.hotel.capacity-confirmedUnits),note:'Số chỗ hiển thị là ước tính từ booking đã xác nhận; yêu cầu đang chờ có thể làm thay đổi khả năng nhận bé.'})}
async function listBookings(db,url){const where=[],args=[];const status=sanitizeStatus(url.searchParams.get('status'));const type=url.searchParams.get('type');const from=url.searchParams.get('from');const to=url.searchParams.get('to');const q=String(url.searchParams.get('q')||'').trim().slice(0,80);if(status){where.push(`status = ?${args.length+1}`);args.push(status)}if(type==='appointment'||type==='hotel'){where.push(`type = ?${args.length+1}`);args.push(type)}if(/^\d{4}-\d{2}-\d{2}$/.test(from||'')){where.push(`date(created_at) >= ?${args.length+1}`);args.push(from)}if(/^\d{4}-\d{2}-\d{2}$/.test(to||'')){where.push(`date(created_at) <= ?${args.length+1}`);args.push(to)}if(q){where.push(`(code LIKE ?${args.length+1} OR owner_name LIKE ?${args.length+2} OR phone LIKE ?${args.length+3} OR pet_name LIKE ?${args.length+4})`);const like=`%${q}%`;args.push(like,like,like,like)}const sql=`SELECT * FROM bookings ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY created_at DESC LIMIT 200`;const stmt=db.prepare(sql);const{results}=args.length?await stmt.bind(...args).run():await stmt.run();return json({bookings:results||[]})}
async function updateBooking(db,code,body){const status=sanitizeStatus(body.status);if(!status)return json({error:'STATUS_INVALID',allowed:ALLOWED_STATUSES},400);const adminNote=String(body.adminNote||'').trim().replace(/[<>]/g,'').slice(0,1200);const priceQuote=body.priceQuote===''||body.priceQuote==null?null:Number(body.priceQuote);if(priceQuote!=null&&(!Number.isFinite(priceQuote)||priceQuote<0||priceQuote>1000000000))return json({error:'PRICE_QUOTE_INVALID'},400);const now=new Date().toISOString();const result=await db.prepare(`UPDATE bookings SET status=?1,admin_note=?2,price_quote=?3,updated_at=?4 WHERE code=?5`).bind(status,adminNote,priceQuote,now,code).run();if(!result.meta||Number(result.meta.changes||0)<1)return json({error:'BOOKING_NOT_FOUND'},404);return json({ok:true,code,status,updatedAt:now})}
async function updateSettings(db,body){const entries=Object.entries(body||{}).filter(([key])=>SETTING_KEYS.has(key));if(!entries.length)return json({error:'NO_VALID_SETTINGS'},400);const now=new Date().toISOString();const statements=[];for(const[key,raw]of entries){const value=sanitizeSettingValue(key,raw);if(value==null)return json({error:'SETTING_VALUE_INVALID',key},400);statements.push(db.prepare(`INSERT INTO settings(key,value,updated_at) VALUES(?1,?2,?3) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).bind(key,value,now))}await db.batch(statements);return json({ok:true,settings:await getSettings(db)})}
async function hotelBoard(db,url){const from=/^\d{4}-\d{2}-\d{2}$/.test(url.searchParams.get('from')||'')?url.searchParams.get('from'):new Date().toISOString().slice(0,10);const days=Math.min(31,Math.max(1,Number(url.searchParams.get('days')||14)));const start=new Date(`${from}T00:00:00Z`);if(!Number.isFinite(start.valueOf()))return json({error:'FROM_INVALID'},400);const settings=await getSettings(db);const capacity=Number(settings.hotel_capacity);const rows=[];for(let i=0;i<days;i+=1){const day=new Date(start.valueOf()+i*86400000).toISOString().slice(0,10);const next=new Date(start.valueOf()+(i+1)*86400000).toISOString().slice(0,10);const{results}=await db.prepare(`SELECT status,COALESCE(SUM(quantity),0) AS units FROM bookings WHERE type='hotel' AND status IN ('PENDING_CONFIRMATION','CONFIRMED') AND checkin_date < ?1 AND checkout_date > ?2 GROUP BY status`).bind(next,day).run();const map=Object.fromEntries((results||[]).map(row=>[row.status,Number(row.units||0)]));rows.push({date:day,capacity:Number.isInteger(capacity)&&capacity>0?capacity:null,confirmed:map.CONFIRMED||0,pending:map.PENDING_CONFIRMATION||0})}return json({from,days,rows})}
async function route(request,env){const url=new URL(request.url);const path=url.pathname.replace(/\/+$/,'')||'/';if(path==='/health'&&request.method==='GET')return json({ok:true,service:'lumi-pet-api',time:new Date().toISOString()});if(path==='/api/public/config'&&request.method==='GET')return json(publicConfig(await getSettings(env.DB)));if(path==='/api/availability'&&request.method==='GET')return publicAvailability(env.DB,url);if(path==='/api/bookings'&&request.method==='POST'){const body=await parseJson(request);const validation=validateBooking(body);if(!validation.ok)return json({error:validation.error},400);try{return json(await insertBooking(env.DB,validation.data),201)}catch(error){if(String(error?.message||error).includes('UNIQUE'))return json({error:'BOOKING_CODE_EXISTS'},409);throw error}}if(path.startsWith('/api/admin/')){if(!adminAuthorized(request,env))return json({error:'UNAUTHORIZED'},401);if(path==='/api/admin/bookings'&&request.method==='GET')return listBookings(env.DB,url);if(path==='/api/admin/settings'&&request.method==='GET')return json({settings:await getSettings(env.DB)});if(path==='/api/admin/settings'&&request.method==='PUT')return updateSettings(env.DB,await parseJson(request));if(path==='/api/admin/hotel-board'&&request.method==='GET')return hotelBoard(env.DB,url);const m=path.match(/^\/api\/admin\/bookings\/([A-Z0-9-]+)$/);if(m&&request.method==='PATCH')return updateBooking(env.DB,m[1],await parseJson(request));return json({error:'NOT_FOUND'},404)}return json({error:'NOT_FOUND'},404)}
export default{async fetch(request,env){const cors=corsFor(request,env);if(!cors.ok)return json({error:'ORIGIN_NOT_ALLOWED'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors.headers});try{return withCors(await route(request,env),cors.headers)}catch(error){const message=String(error?.message||error);if(message==='BODY_TOO_LARGE')return withCors(json({error:message},413),cors.headers);if(message==='BODY_INVALID_JSON')return withCors(json({error:message},400),cors.headers);if(/no such table/i.test(message))return withCors(json({error:'DB_NOT_INITIALIZED',message:'Apply D1 migrations before using the API.'},503),cors.headers);console.error('LUMI_API_ERROR',{path:new URL(request.url).pathname,message:message.slice(0,300)});return withCors(json({error:'INTERNAL_ERROR'},500),cors.headers)}}};
